const SITE_DATA = {
  zh: {
    labels: {
      pageTitle: "贾唯｜个人学术主页",
      profileAlt: "贾唯的个人证件照",
      navBiography: "个人简介",
      navNews: "动态",
      navPublications: "论文",
      navExperience: "经历",
      navEducation: "教育",
      navHonors: "荣誉",
      aboutLabel: "ABOUT ME",
      sectionBiography: "个人简介",
      sectionNews: "近期动态",
      sectionPublications: "科研成果",
      sectionExperience: "实习与项目经历",
      sectionEducation: "教育经历",
      sectionHonors: "荣誉奖项",
      lastUpdated: "最后更新",
    },
    profile: {
      shortName: "贾唯",
      name: "贾唯",
      englishName: "Wei Jia",
      role: "中国科学院大学五年级博士研究生",
      affiliation: "中国科学院空天信息创新研究院 · 目标认知与应用技术国家重点实验室",
      footerName: "贾唯 · Wei Jia",
      publicationSummary: "以第一作者或通讯作者身份围绕多模态推理、RLVR、信息抽取与事件推理开展研究；参与技术报告 1 篇，发表或录用 CCF-A 论文 2 篇、SCI 期刊论文 2 篇，并有多篇工作在投。",
      biography: [
        "贾唯现为**中国科学院大学**五年级博士研究生，在中国科学院空天信息创新研究院**目标认知与应用技术国家重点实验室**开展研究，预计于 2027 年 6 月毕业。2022 年获得**天津大学**电子信息工程学士学位，专业排名前 5%，并推免直博。",
        "研究方向包括 **多模态大模型**、多模态推理与自然语言处理，尤其关注如何提升模型的多模态理解和推理能力。先后在智谱 AI 与阿里巴巴高德地图开展多模态大模型和视频推理相关研发实践。",
      ],
      facts: [
        { icon: "📍", text: "北京，中国" },
        { icon: "✉", text: "jiawei22@mails.ucas.ac.cn" },
        { icon: "🎓", text: "预计 2027 年 6 月毕业" },
      ],
      links: [
        { label: "Email", href: "mailto:jiawei22@mails.ucas.ac.cn" },
        { label: "GitHub", href: "https://github.com/jiaweidoris" },
      ],
      interests: ["多模态大模型", "多模态推理", "自然语言处理"],
    },
    opportunity: {
      message: "🔥 我正在参加秋招，积极寻找互联网行业的工作与实习机会，欢迎与我联系！",
      emailLabel: "📧 邮箱",
      email: "jiawei22@mails.ucas.ac.cn",
      wechatLabel: "💬 微信",
      wechat: "JiaWeiDoris",
    },
    news: [
      { date: "2026.07", text: "一篇论文被 Neurocomputing 录用。" },
      { date: "2025.10", text: "一篇论文发表于 ACM Multimedia 2025。" },
      { date: "2025.09", text: "一篇论文发表于 Electronics。" },
      { date: "2025.07", text: "一篇论文发表于 ACL 2025。" },
      { date: "2025.07", text: "一篇技术报告发布于 arXiv。" },
    ],
    publicationGroups: [
      {
        title: "发表与录用",
        items: [
          {
            badge: "ACM MM\n2025",
            image: "assets/publications/umere-figure-3.jpg",
            imageAlt: "U-MERE Figure 3：协同建模与顺序敏感机制框架图",
            title: "U-MERE: Unconstrained Multimodal Entity and Relation Extraction with Collaborative Modeling and Order-Sensitive Optimization",
            authors: "Wei Jia, Li Jin, Kaiwen Wei, Yuying Shang, Nayu Liu, Zhicong Lu, Qing Liu, Linhao Zhang, Jiang Zhong, Yanfeng Hu",
            venue: "ACM Multimedia 2025 · CCF-A · 第一作者",
            description: "面向无约束多模态实体关系联合抽取，研究跨模态实体与关系的协同建模及顺序敏感优化。",
            links: [{ label: "Paper", href: "https://doi.org/10.1145/3746027.3755397" }],
          },
          {
            badge: "ACL\n2025",
            image: "assets/publications/piper-figure-3.jpg",
            imageAlt: "PIPER Figure 3：去偏与蒸馏增强监督微调框架图",
            title: "PIPER: Benchmarking and Prompting Event Reasoning Boundary of LLMs via Debiasing-Distillation Enhanced Tuning",
            authors: "Zhicong Lu, Changyuan Tian, Peiguang Li, Li Jin, Sirui Wang, Wei Jia, Ying Shen, Guangluan Xu",
            venue: "ACL 2025 · CCF-A · 第六作者",
            description: "构建上下文事件推理基准，并通过去偏与蒸馏增强的监督微调提升模型事件推理能力。",
            links: [{ label: "Paper", href: "https://aclanthology.org/2025.acl-long.1389/" }],
          },
          {
            badge: "Neuro-\ncomputing",
            image: "assets/publications/mugre-figure-3.jpg",
            imageAlt: "MuGRE Figure 3：多粒度动态特征重排整体框架图",
            title: "Multi-Grained Dynamic Feature Resorter with Curriculum Bootstrapping for Multimodal Entity and Relation Extraction",
            authors: "Wei Jia, Zhicong Lu, Li Jin, Linhao Zhang, Kaiwen Wei, Qing Liu, Liang Zhao, Yanfeng Hu",
            venue: "Neurocomputing · SCI · 第一作者 · 已录用",
            description: "通过可学习跨模态交互与课程式动态排序降低多模态抽取中的无关视觉噪声。",
            links: [{ label: "Paper", href: "https://doi.org/10.1016/j.neucom.2026.134606" }],
          },
          {
            badge: "Electronics\n2025",
            image: "assets/publications/timeweaver.jpg",
            imageAlt: "TimeWeaver 时序混合专家、双向预训练与强化学习整体框架图",
            title: "TimeWeaver: Orchestrating Narrative Order via Temporal Mixture-of-Experts Integrated Event–Order Bidirectional Pretraining and Multi-Granular Reward Reinforcement Learning",
            authors: "Zhicong Lu, Wei Jia, Changyuan Tian, Li Jin, Yang Bai, Guangluan Xu",
            venue: "Electronics 2025, 14, 3880 · SCI · 第二作者",
            description: "结合事件顺序双向预训练、时序混合专家与多粒度奖励，提升叙事生成的时序合理性。",
            links: [{ label: "Paper", href: "https://doi.org/10.3390/electronics14193880" }],
          },
        ],
      },
      {
        title: "在投工作",
        items: [
          {
            badge: "Under\nReview",
            title: "CAVE: Competence-Aware Visual Boundary Evidence Alignment for Video Temporal Grounding",
            authors: "Wei Jia (First Author), et al.",
            venue: "AAAI · 第一作者 · 已投稿",
            description: "研究视频时序定位中的视觉证据—时间戳错配，并以能力感知的边界证据对齐改善高精度区间预测。",
          },
          {
            badge: "Under\nReview",
            title: "CORA: Analyzing and Bridging the Thinking–Answer Gap in Multimodal RLVR via Consistency-Oriented Reasoning Alignment",
            image: "assets/publications/cora-figure-3.jpg",
            imageAlt: "CORA Figure 3：一致性奖励模型与推理对齐整体框架图",
            authors: "Wei Jia (Corresponding Author), et al.",
            venue: "EMNLP · 通讯作者 · 已投稿 · Meta Review 3",
            description: "分析多模态 RLVR 中思维链与最终答案的一致性问题，并通过一致性导向的奖励实现协同对齐。",
            links: [{ label: "arXiv", href: "https://arxiv.org/abs/2606.14691" }],
          },
          {
            badge: "Under\nReview",
            title: "HiSR: Hindsight-Information-Modulated Segmental Process Rewards for Multi-Turn Agentic Reinforcement Learning",
            image: "assets/publications/hisr-figure-2.jpg",
            imageAlt: "HiSR Figure 2：后见信息调制分段过程奖励方法框架图",
            authors: "Wei Jia (Second Author), et al.",
            venue: "AAAI · 第二作者 · 已投稿",
            description: "将长程交互拆分为可评估的决策片段，并利用后见信息构造细粒度过程奖励。",
            links: [{ label: "arXiv", href: "https://arxiv.org/abs/2603.18683" }],
          },
        ],
      },
      {
        title: "技术报告",
        items: [
          {
            badge: "GLM-V\nReport",
            image: "assets/publications/glmv-figure-2.jpg",
            imageAlt: "GLM-V Figure 2：GLM-4.1V-Thinking、GLM-4.5V 与 GLM-4.6V 共享架构图",
            title: "GLM-4.5V and GLM-4.1V-Thinking: Towards Versatile Multimodal Reasoning with Scalable Reinforcement Learning",
            authors: "GLM-V Team · Contributor",
            venue: "Technical Report · 2025",
            description: "系统介绍通用多模态理解与推理模型的规模化后训练方案，覆盖课程采样、强化学习与视频推理。",
            links: [{ label: "Paper", href: "https://arxiv.org/abs/2507.01006" }],
          },
        ],
      },
    ],
    experience: [
      {
        date: "2026.01–至今",
        logo: "assets/logos/amap.png",
        logoAlt: "高德地图 Logo",
        title: "阿里巴巴高德地图 · 信息业务中心 Research 算法实习生",
        meta: "视频时序定位与强化学习",
        description: "围绕视频时序定位中的视觉证据—时间戳错配开展问题分析、方法设计、训练评测与多尺度验证，相关研究以第一作者投稿 AAAI。",
      },
      {
        date: "2025.03–2026.01",
        logo: "assets/logos/zhipu-ai.svg",
        logoAlt: "智谱 AI Logo",
        title: "北京智谱华章科技有限公司 · AI 院 CogVLM 算法实习生",
        meta: "多模态大模型 SFT / RLVR",
        description: "参与 GLM-4.1V-Thinking、GLM-4.5V 与 GLM-4.6V 训练，负责视频理解与推理数据建设、课程/动态采样、Verifier 调优及统一评测。",
      },
      {
        date: "2023.10–2024.03",
        title: "多模态多任务遥感问答模型研发 · 学生核心参与者",
        meta: "多模态基础模型与指令微调",
        description: "完成遥感图文数据构建、多任务指令化、联合训练、下游迁移与统一评测。",
      },
    ],
    education: [
      {
        date: "2022.09–2027.06",
        logo: "assets/logos/ucas-color.png",
        logoAlt: "中国科学院大学 Logo",
        logoTone: "school",
        title: "中国科学院大学",
        meta: "博士 · 中国科学院空天信息创新研究院 · 北京",
        description: "目标认知与应用技术国家重点实验室，GPA 3.83/4.00。",
      },
      {
        date: "2018.09–2022.07",
        logo: "assets/logos/tianjin-university-color.jpg",
        logoAlt: "天津大学 Logo",
        logoTone: "school",
        title: "天津大学",
        meta: "电子信息工程学士 · 天津",
        description: "专业前 5%，推免直博；双一流、985、211。",
      },
    ],
    honors: [
      { year: "2022–2025", title: "研究生一等学业奖学金" },
      { year: "2022–2026", title: "中国科学院大学学业奖学金" },
      { year: "2021–2022", title: "天津大学优秀毕业生" },
      { year: "2020–2021", title: "天津大学学习优异先进个人" },
      { year: "2018–2022", title: "天津大学三好学生" },
    ],
  },

  en: {
    labels: {
      pageTitle: "Wei Jia | Academic Homepage",
      profileAlt: "Portrait of Wei Jia",
      navBiography: "Biography",
      navNews: "News",
      navPublications: "Publications",
      navExperience: "Experience",
      navEducation: "Education",
      navHonors: "Honors",
      aboutLabel: "ABOUT ME",
      sectionBiography: "Biography",
      sectionNews: "News",
      sectionPublications: "Publications",
      sectionExperience: "Internships & Projects",
      sectionEducation: "Education",
      sectionHonors: "Honors & Awards",
      lastUpdated: "Last updated",
    },
    profile: {
      shortName: "Wei Jia",
      name: "Wei Jia",
      englishName: "贾唯",
      role: "Fifth-Year PhD Candidate at UCAS",
      affiliation: "Aerospace Information Research Institute, CAS · State Key Laboratory of Target Cognition and Application Technology",
      footerName: "Wei Jia · 贾唯",
      publicationSummary: "As a first or corresponding author, I work on multimodal reasoning, RLVR, information extraction, and event reasoning. My portfolio includes one technical report, two published or accepted CCF-A papers, two SCI journal papers, and multiple submissions.",
      biography: [
        "Wei Jia is a fifth-year PhD candidate at the **University of Chinese Academy of Sciences**, conducting research at the **State Key Laboratory of Target Cognition and Application Technology**, Aerospace Information Research Institute, Chinese Academy of Sciences, and expects to graduate in June 2027. Wei received a B.Eng. in Electronic Information Engineering from **Tianjin University** in 2022, ranking in the top 5%, and was directly admitted to the doctoral program.",
        "Wei’s research interests include **multimodal large language models**, multimodal reasoning, and natural language processing, with a particular focus on improving multimodal understanding and reasoning capabilities. Wei has contributed to multimodal foundation model and video reasoning research through internships at Zhipu AI and Alibaba Amap.",
      ],
      facts: [
        { icon: "📍", text: "Beijing, China" },
        { icon: "✉", text: "jiawei22@mails.ucas.ac.cn" },
        { icon: "🎓", text: "Expected graduation: Jun. 2027" },
      ],
      links: [
        { label: "Email", href: "mailto:jiawei22@mails.ucas.ac.cn" },
        { label: "GitHub", href: "https://github.com/jiaweidoris" },
      ],
      interests: ["Multimodal Large Language Models", "Multimodal Reasoning", "Natural Language Processing"],
    },
    opportunity: {
      message: "🔥 I am actively seeking full-time and internship opportunities in the internet and technology industry during the fall recruitment cycle. Please feel free to contact me!",
      emailLabel: "📧 Email",
      email: "jiawei22@mails.ucas.ac.cn",
      wechatLabel: "💬 WeChat",
      wechat: "JiaWeiDoris",
    },
    news: [
      { date: "2026.07", text: "One paper is accepted by Neurocomputing." },
      { date: "2025.10", text: "One paper is published at ACM Multimedia 2025." },
      { date: "2025.09", text: "One paper is published in Electronics." },
      { date: "2025.07", text: "One paper is published at ACL 2025." },
      { date: "2025.07", text: "One technical report is released on arXiv." },
    ],
    publicationGroups: [
      {
        title: "Published & Accepted",
        items: [
          {
            badge: "ACM MM\n2025",
            image: "assets/publications/umere-figure-3.jpg",
            imageAlt: "U-MERE Figure 3: collaborative modeling and order-sensitive mechanism",
            title: "U-MERE: Unconstrained Multimodal Entity and Relation Extraction with Collaborative Modeling and Order-Sensitive Optimization",
            authors: "Wei Jia, Li Jin, Kaiwen Wei, Yuying Shang, Nayu Liu, Zhicong Lu, Qing Liu, Linhao Zhang, Jiang Zhong, Yanfeng Hu",
            venue: "ACM Multimedia 2025 · CCF-A · First Author",
            description: "Studies collaborative modeling and order-sensitive optimization for unconstrained multimodal entity and relation extraction.",
            links: [{ label: "Paper", href: "https://doi.org/10.1145/3746027.3755397" }],
          },
          {
            badge: "ACL\n2025",
            image: "assets/publications/piper-figure-3.jpg",
            imageAlt: "PIPER Figure 3: debiasing- and distillation-enhanced supervised fine-tuning framework",
            title: "PIPER: Benchmarking and Prompting Event Reasoning Boundary of LLMs via Debiasing-Distillation Enhanced Tuning",
            authors: "Zhicong Lu, Changyuan Tian, Peiguang Li, Li Jin, Sirui Wang, Wei Jia, Ying Shen, Guangluan Xu",
            venue: "ACL 2025 · CCF-A · Sixth Author",
            description: "Builds a contextual event-reasoning benchmark and improves model capability through debiasing and distillation-enhanced supervised tuning.",
            links: [{ label: "Paper", href: "https://aclanthology.org/2025.acl-long.1389/" }],
          },
          {
            badge: "Neuro-\ncomputing",
            image: "assets/publications/mugre-figure-3.jpg",
            imageAlt: "MuGRE Figure 3: multi-grained dynamic feature resorting framework",
            title: "Multi-Grained Dynamic Feature Resorter with Curriculum Bootstrapping for Multimodal Entity and Relation Extraction",
            authors: "Wei Jia, Zhicong Lu, Li Jin, Linhao Zhang, Kaiwen Wei, Qing Liu, Liang Zhao, Yanfeng Hu",
            venue: "Neurocomputing · SCI · First Author · Accepted",
            description: "Reduces irrelevant visual noise through learnable cross-modal interaction and curriculum-based dynamic reordering.",
            links: [{ label: "Paper", href: "https://doi.org/10.1016/j.neucom.2026.134606" }],
          },
          {
            badge: "Electronics\n2025",
            image: "assets/publications/timeweaver.jpg",
            imageAlt: "TimeWeaver framework with temporal mixture-of-experts, bidirectional pretraining, and reinforcement learning",
            title: "TimeWeaver: Orchestrating Narrative Order via Temporal Mixture-of-Experts Integrated Event–Order Bidirectional Pretraining and Multi-Granular Reward Reinforcement Learning",
            authors: "Zhicong Lu, Wei Jia, Changyuan Tian, Li Jin, Yang Bai, Guangluan Xu",
            venue: "Electronics 2025, 14, 3880 · SCI · Second Author",
            description: "Combines bidirectional event-order pretraining, temporal mixture-of-experts, and multi-granular rewards for narrative generation.",
            links: [{ label: "Paper", href: "https://doi.org/10.3390/electronics14193880" }],
          },
        ],
      },
      {
        title: "Under Review",
        items: [
          {
            badge: "Under\nReview",
            title: "CAVE: Competence-Aware Visual Boundary Evidence Alignment for Video Temporal Grounding",
            authors: "Wei Jia (First Author), et al.",
            venue: "AAAI · First Author · Under Review",
            description: "Addresses visual-evidence–timestamp mismatch in video temporal grounding through competence-aware boundary evidence alignment.",
          },
          {
            badge: "Under\nReview",
            title: "CORA: Analyzing and Bridging the Thinking–Answer Gap in Multimodal RLVR via Consistency-Oriented Reasoning Alignment",
            image: "assets/publications/cora-figure-3.jpg",
            imageAlt: "CORA Figure 3: consistency reward model and reasoning alignment framework",
            authors: "Wei Jia (Corresponding Author), et al.",
            venue: "EMNLP · Corresponding Author · Under Review · Meta Review 3",
            description: "Studies consistency between reasoning traces and final answers in multimodal RLVR and aligns them through a consistency-oriented reward strategy.",
            links: [{ label: "arXiv", href: "https://arxiv.org/abs/2606.14691" }],
          },
          {
            badge: "Under\nReview",
            title: "HiSR: Hindsight-Information-Modulated Segmental Process Rewards for Multi-Turn Agentic Reinforcement Learning",
            image: "assets/publications/hisr-figure-2.jpg",
            imageAlt: "HiSR Figure 2: hindsight-information-modulated segmental process reward framework",
            authors: "Wei Jia (Second Author), et al.",
            venue: "AAAI · Second Author · Under Review",
            description: "Decomposes long-horizon interactions into assessable decision segments and provides hindsight-modulated process rewards.",
            links: [{ label: "arXiv", href: "https://arxiv.org/abs/2603.18683" }],
          },
        ],
      },
      {
        title: "Technical Report",
        items: [
          {
            badge: "GLM-V\nReport",
            image: "assets/publications/glmv-figure-2.jpg",
            imageAlt: "GLM-V Figure 2: shared architecture of GLM-4.1V-Thinking, GLM-4.5V, and GLM-4.6V",
            title: "GLM-4.5V and GLM-4.1V-Thinking: Towards Versatile Multimodal Reasoning with Scalable Reinforcement Learning",
            authors: "GLM-V Team · Contributor",
            venue: "Technical Report · 2025",
            description: "Presents a scalable post-training recipe for multimodal understanding and reasoning, including curriculum sampling, reinforcement learning, and video reasoning.",
            links: [{ label: "Paper", href: "https://arxiv.org/abs/2507.01006" }],
          },
        ],
      },
    ],
    experience: [
      {
        date: "2026.01–Present",
        logo: "assets/logos/amap.png",
        logoAlt: "Amap logo",
        title: "Alibaba Amap · Research Algorithm Intern",
        meta: "Video temporal grounding and reinforcement learning",
        description: "Conducted problem analysis, method design, training, evaluation, and multi-scale validation for visual-evidence–timestamp mismatch in video temporal grounding; organized as a first-author AAAI submission.",
      },
      {
        date: "2025.03–2026.01",
        logo: "assets/logos/zhipu-ai.svg",
        logoAlt: "Zhipu AI logo",
        title: "Zhipu AI · CogVLM Algorithm Intern",
        meta: "Multimodal model SFT / RLVR",
        description: "Contributed to GLM-4.1V-Thinking, GLM-4.5V, and GLM-4.6V through video reasoning data, curriculum and dynamic sampling, verifier tuning, and unified evaluation.",
      },
      {
        date: "2023.10–2024.03",
        title: "Multitask Remote-Sensing VQA Model · Student Core Contributor",
        meta: "Multimodal foundation models and instruction tuning",
        description: "Built remote-sensing image–text data and completed multitask instruction conversion, joint training, downstream transfer, and evaluation.",
      },
    ],
    education: [
      {
        date: "2022.09–2027.06",
        logo: "assets/logos/ucas-color.png",
        logoAlt: "University of Chinese Academy of Sciences logo",
        logoTone: "school",
        title: "University of Chinese Academy of Sciences",
        meta: "PhD · Aerospace Information Research Institute, CAS · Beijing",
        description: "State Key Laboratory of Target Cognition and Application Technology · GPA 3.83/4.00.",
      },
      {
        date: "2018.09–2022.07",
        logo: "assets/logos/tianjin-university-color.jpg",
        logoAlt: "Tianjin University logo",
        logoTone: "school",
        title: "Tianjin University",
        meta: "B.Eng. in Electronic Information Engineering · Tianjin",
        description: "Top 5% with direct PhD recommendation · Double First-Class · 985 · 211.",
      },
    ],
    honors: [
      { year: "2022–2025", title: "Graduate First-Class Academic Scholarship" },
      { year: "2022–2026", title: "UCAS Academic Scholarship" },
      { year: "2021–2022", title: "Outstanding Graduate, Tianjin University" },
      { year: "2020–2021", title: "Advanced Individual in Academic Excellence" },
      { year: "2018–2022", title: "Outstanding Student, Tianjin University" },
    ],
  },
};
